# Generated by Django 4.2.7 on 2023-11-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_password_remove_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='is_deleted',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='is_deleted',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='roleaction',
            old_name='is_deleted',
            new_name='deleted',
        ),
    ]
