# Generated by Django 4.2.7 on 2023-11-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_is_deleted_action_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='actions',
            field=models.ManyToManyField(related_name='roles', to='accounts.action'),
        ),
        migrations.DeleteModel(
            name='RoleAction',
        ),
    ]
