# Generated by Django 4.2.7 on 2023-11-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='is_deleted',
            new_name='deleted',
        ),
    ]
